// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shigabutdinoff/gophermart/internal/balance"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// Balance provides a mock function for the type MockReader
func (_mock *MockReader) Balance(ctx context.Context, userID int64) (balance.Balance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Balance")
	}

	var r0 balance.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (balance.Balance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) balance.Balance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(balance.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_Balance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Balance'
type MockReader_Balance_Call struct {
	*mock.Call
}

// Balance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockReader_Expecter) Balance(ctx any, userID any) *MockReader_Balance_Call {
	return &MockReader_Balance_Call{Call: _e.mock.On("Balance", ctx, userID)}
}

func (_c *MockReader_Balance_Call) Run(run func(ctx context.Context, userID int64)) *MockReader_Balance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReader_Balance_Call) Return(balance1 balance.Balance, err error) *MockReader_Balance_Call {
	_c.Call.Return(balance1, err)
	return _c
}

func (_c *MockReader_Balance_Call) RunAndReturn(run func(ctx context.Context, userID int64) (balance.Balance, error)) *MockReader_Balance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWithdrawalLister creates a new instance of MockWithdrawalLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWithdrawalLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWithdrawalLister {
	mock := &MockWithdrawalLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWithdrawalLister is an autogenerated mock type for the WithdrawalLister type
type MockWithdrawalLister struct {
	mock.Mock
}

type MockWithdrawalLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWithdrawalLister) EXPECT() *MockWithdrawalLister_Expecter {
	return &MockWithdrawalLister_Expecter{mock: &_m.Mock}
}

// ListWithdrawals provides a mock function for the type MockWithdrawalLister
func (_mock *MockWithdrawalLister) ListWithdrawals(ctx context.Context, userID int64) ([]balance.Withdrawal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawals")
	}

	var r0 []balance.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]balance.Withdrawal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []balance.Withdrawal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]balance.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWithdrawalLister_ListWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithdrawals'
type MockWithdrawalLister_ListWithdrawals_Call struct {
	*mock.Call
}

// ListWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockWithdrawalLister_Expecter) ListWithdrawals(ctx any, userID any) *MockWithdrawalLister_ListWithdrawals_Call {
	return &MockWithdrawalLister_ListWithdrawals_Call{Call: _e.mock.On("ListWithdrawals", ctx, userID)}
}

func (_c *MockWithdrawalLister_ListWithdrawals_Call) Run(run func(ctx context.Context, userID int64)) *MockWithdrawalLister_ListWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWithdrawalLister_ListWithdrawals_Call) Return(withdrawals []balance.Withdrawal, err error) *MockWithdrawalLister_ListWithdrawals_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockWithdrawalLister_ListWithdrawals_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]balance.Withdrawal, error)) *MockWithdrawalLister_ListWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}
