// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shigabutdinoff/gophermart/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoginPasswords creates a new instance of MockLoginPasswords. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginPasswords(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginPasswords {
	mock := &MockLoginPasswords{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginPasswords is an autogenerated mock type for the loginPasswords type
type MockLoginPasswords struct {
	mock.Mock
}

type MockLoginPasswords_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginPasswords) EXPECT() *MockLoginPasswords_Expecter {
	return &MockLoginPasswords_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockLoginPasswords
func (_mock *MockLoginPasswords) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginPasswords_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockLoginPasswords_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockLoginPasswords_Expecter) Hash(password any) *MockLoginPasswords_Hash_Call {
	return &MockLoginPasswords_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockLoginPasswords_Hash_Call) Run(run func(password string)) *MockLoginPasswords_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoginPasswords_Hash_Call) Return(s string, err error) *MockLoginPasswords_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLoginPasswords_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockLoginPasswords_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockLoginPasswords
func (_mock *MockLoginPasswords) Verify(passwordHash string, password string) error {
	ret := _mock.Called(passwordHash, password)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(passwordHash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoginPasswords_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockLoginPasswords_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - passwordHash string
//   - password string
func (_e *MockLoginPasswords_Expecter) Verify(passwordHash any, password any) *MockLoginPasswords_Verify_Call {
	return &MockLoginPasswords_Verify_Call{Call: _e.mock.On("Verify", passwordHash, password)}
}

func (_c *MockLoginPasswords_Verify_Call) Run(run func(passwordHash string, password string)) *MockLoginPasswords_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoginPasswords_Verify_Call) Return(err error) *MockLoginPasswords_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginPasswords_Verify_Call) RunAndReturn(run func(passwordHash string, password string) error) *MockLoginPasswords_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserCreator creates a new instance of MockUserCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCreator {
	mock := &MockUserCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCreator is an autogenerated mock type for the UserCreator type
type MockUserCreator struct {
	mock.Mock
}

type MockUserCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCreator) EXPECT() *MockUserCreator_Expecter {
	return &MockUserCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserCreator
func (_mock *MockUserCreator) Create(ctx context.Context, login string, passwordHash string) (auth.User, error) {
	ret := _mock.Called(ctx, login, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 auth.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (auth.User, error)); ok {
		return returnFunc(ctx, login, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) auth.User); ok {
		r0 = returnFunc(ctx, login, passwordHash)
	} else {
		r0 = ret.Get(0).(auth.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - passwordHash string
func (_e *MockUserCreator_Expecter) Create(ctx any, login any, passwordHash any) *MockUserCreator_Create_Call {
	return &MockUserCreator_Create_Call{Call: _e.mock.On("Create", ctx, login, passwordHash)}
}

func (_c *MockUserCreator_Create_Call) Run(run func(ctx context.Context, login string, passwordHash string)) *MockUserCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserCreator_Create_Call) Return(user auth.User, err error) *MockUserCreator_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserCreator_Create_Call) RunAndReturn(run func(ctx context.Context, login string, passwordHash string) (auth.User, error)) *MockUserCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserFinder creates a new instance of MockUserFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFinder {
	mock := &MockUserFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserFinder is an autogenerated mock type for the UserFinder type
type MockUserFinder struct {
	mock.Mock
}

type MockUserFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFinder) EXPECT() *MockUserFinder_Expecter {
	return &MockUserFinder_Expecter{mock: &_m.Mock}
}

// FindByLogin provides a mock function for the type MockUserFinder
func (_mock *MockUserFinder) FindByLogin(ctx context.Context, login string) (auth.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindByLogin")
	}

	var r0 auth.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(auth.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserFinder_FindByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLogin'
type MockUserFinder_FindByLogin_Call struct {
	*mock.Call
}

// FindByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockUserFinder_Expecter) FindByLogin(ctx any, login any) *MockUserFinder_FindByLogin_Call {
	return &MockUserFinder_FindByLogin_Call{Call: _e.mock.On("FindByLogin", ctx, login)}
}

func (_c *MockUserFinder_FindByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserFinder_FindByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserFinder_FindByLogin_Call) Return(user auth.User, err error) *MockUserFinder_FindByLogin_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserFinder_FindByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (auth.User, error)) *MockUserFinder_FindByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockPasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordHasher_Expecter) Hash(password any) *MockPasswordHasher_Hash_Call {
	return &MockPasswordHasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *MockPasswordHasher_Hash_Call) Run(run func(password string)) *MockPasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) Return(s string, err error) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordVerifier creates a new instance of MockPasswordVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordVerifier {
	mock := &MockPasswordVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordVerifier is an autogenerated mock type for the PasswordVerifier type
type MockPasswordVerifier struct {
	mock.Mock
}

type MockPasswordVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordVerifier) EXPECT() *MockPasswordVerifier_Expecter {
	return &MockPasswordVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockPasswordVerifier
func (_mock *MockPasswordVerifier) Verify(passwordHash string, password string) error {
	ret := _mock.Called(passwordHash, password)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(passwordHash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - passwordHash string
//   - password string
func (_e *MockPasswordVerifier_Expecter) Verify(passwordHash any, password any) *MockPasswordVerifier_Verify_Call {
	return &MockPasswordVerifier_Verify_Call{Call: _e.mock.On("Verify", passwordHash, password)}
}

func (_c *MockPasswordVerifier_Verify_Call) Run(run func(passwordHash string, password string)) *MockPasswordVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) Return(err error) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) RunAndReturn(run func(passwordHash string, password string) error) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockTokenIssuer
func (_mock *MockTokenIssuer) Issue(userID int64) (auth.IssuedToken, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 auth.IssuedToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (auth.IssuedToken, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) auth.IssuedToken); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(auth.IssuedToken)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockTokenIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - userID int64
func (_e *MockTokenIssuer_Expecter) Issue(userID any) *MockTokenIssuer_Issue_Call {
	return &MockTokenIssuer_Issue_Call{Call: _e.mock.On("Issue", userID)}
}

func (_c *MockTokenIssuer_Issue_Call) Run(run func(userID int64)) *MockTokenIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) Return(issuedToken auth.IssuedToken, err error) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(issuedToken, err)
	return _c
}

func (_c *MockTokenIssuer_Issue_Call) RunAndReturn(run func(userID int64) (auth.IssuedToken, error)) *MockTokenIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}
