// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"time"

	"github.com/riverqueue/river"
	"github.com/riverqueue/river/rivertype"
	"github.com/shigabutdinoff/gophermart/internal/accrual"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccrualClient creates a new instance of MockAccrualClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccrualClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccrualClient {
	mock := &MockAccrualClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccrualClient is an autogenerated mock type for the AccrualClient type
type MockAccrualClient struct {
	mock.Mock
}

type MockAccrualClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccrualClient) EXPECT() *MockAccrualClient_Expecter {
	return &MockAccrualClient_Expecter{mock: &_m.Mock}
}

// OrderInfo provides a mock function for the type MockAccrualClient
func (_mock *MockAccrualClient) OrderInfo(ctx context.Context, number string) (accrual.OrderInfo, error) {
	ret := _mock.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for OrderInfo")
	}

	var r0 accrual.OrderInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (accrual.OrderInfo, error)); ok {
		return returnFunc(ctx, number)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) accrual.OrderInfo); ok {
		r0 = returnFunc(ctx, number)
	} else {
		r0 = ret.Get(0).(accrual.OrderInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, number)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccrualClient_OrderInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderInfo'
type MockAccrualClient_OrderInfo_Call struct {
	*mock.Call
}

// OrderInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockAccrualClient_Expecter) OrderInfo(ctx any, number any) *MockAccrualClient_OrderInfo_Call {
	return &MockAccrualClient_OrderInfo_Call{Call: _e.mock.On("OrderInfo", ctx, number)}
}

func (_c *MockAccrualClient_OrderInfo_Call) Run(run func(ctx context.Context, number string)) *MockAccrualClient_OrderInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccrualClient_OrderInfo_Call) Return(orderInfo accrual.OrderInfo, err error) *MockAccrualClient_OrderInfo_Call {
	_c.Call.Return(orderInfo, err)
	return _c
}

func (_c *MockAccrualClient_OrderInfo_Call) RunAndReturn(run func(ctx context.Context, number string) (accrual.OrderInfo, error)) *MockAccrualClient_OrderInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInserter creates a new instance of MockInserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInserter {
	mock := &MockInserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInserter is an autogenerated mock type for the Inserter type
type MockInserter struct {
	mock.Mock
}

type MockInserter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInserter) EXPECT() *MockInserter_Expecter {
	return &MockInserter_Expecter{mock: &_m.Mock}
}

// InsertTx provides a mock function for the type MockInserter
func (_mock *MockInserter) InsertTx(ctx context.Context, tx *sql.Tx, args river.JobArgs, opts *river.InsertOpts) (*rivertype.JobInsertResult, error) {
	ret := _mock.Called(ctx, tx, args, opts)

	if len(ret) == 0 {
		panic("no return value specified for InsertTx")
	}

	var r0 *rivertype.JobInsertResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, river.JobArgs, *river.InsertOpts) (*rivertype.JobInsertResult, error)); ok {
		return returnFunc(ctx, tx, args, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.Tx, river.JobArgs, *river.InsertOpts) *rivertype.JobInsertResult); ok {
		r0 = returnFunc(ctx, tx, args, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rivertype.JobInsertResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.Tx, river.JobArgs, *river.InsertOpts) error); ok {
		r1 = returnFunc(ctx, tx, args, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInserter_InsertTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTx'
type MockInserter_InsertTx_Call struct {
	*mock.Call
}

// InsertTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - args river.JobArgs
//   - opts *river.InsertOpts
func (_e *MockInserter_Expecter) InsertTx(ctx any, tx any, args any, opts any) *MockInserter_InsertTx_Call {
	return &MockInserter_InsertTx_Call{Call: _e.mock.On("InsertTx", ctx, tx, args, opts)}
}

func (_c *MockInserter_InsertTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, args river.JobArgs, opts *river.InsertOpts)) *MockInserter_InsertTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.Tx
		if args[1] != nil {
			arg1 = args[1].(*sql.Tx)
		}
		var arg2 river.JobArgs
		if args[2] != nil {
			arg2 = args[2].(river.JobArgs)
		}
		var arg3 *river.InsertOpts
		if args[3] != nil {
			arg3 = args[3].(*river.InsertOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInserter_InsertTx_Call) Return(jobInsertResult *rivertype.JobInsertResult, err error) *MockInserter_InsertTx_Call {
	_c.Call.Return(jobInsertResult, err)
	return _c
}

func (_c *MockInserter_InsertTx_Call) RunAndReturn(run func(ctx context.Context, tx *sql.Tx, args river.JobArgs, opts *river.InsertOpts) (*rivertype.JobInsertResult, error)) *MockInserter_InsertTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueController creates a new instance of MockQueueController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueController {
	mock := &MockQueueController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueController is an autogenerated mock type for the QueueController type
type MockQueueController struct {
	mock.Mock
}

type MockQueueController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueController) EXPECT() *MockQueueController_Expecter {
	return &MockQueueController_Expecter{mock: &_m.Mock}
}

// QueuePause provides a mock function for the type MockQueueController
func (_mock *MockQueueController) QueuePause(ctx context.Context, name string, opts *river.QueuePauseOpts) error {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for QueuePause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *river.QueuePauseOpts) error); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueController_QueuePause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueuePause'
type MockQueueController_QueuePause_Call struct {
	*mock.Call
}

// QueuePause is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts *river.QueuePauseOpts
func (_e *MockQueueController_Expecter) QueuePause(ctx any, name any, opts any) *MockQueueController_QueuePause_Call {
	return &MockQueueController_QueuePause_Call{Call: _e.mock.On("QueuePause", ctx, name, opts)}
}

func (_c *MockQueueController_QueuePause_Call) Run(run func(ctx context.Context, name string, opts *river.QueuePauseOpts)) *MockQueueController_QueuePause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *river.QueuePauseOpts
		if args[2] != nil {
			arg2 = args[2].(*river.QueuePauseOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueController_QueuePause_Call) Return(err error) *MockQueueController_QueuePause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueController_QueuePause_Call) RunAndReturn(run func(ctx context.Context, name string, opts *river.QueuePauseOpts) error) *MockQueueController_QueuePause_Call {
	_c.Call.Return(run)
	return _c
}

// QueueResume provides a mock function for the type MockQueueController
func (_mock *MockQueueController) QueueResume(ctx context.Context, name string, opts *river.QueuePauseOpts) error {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for QueueResume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *river.QueuePauseOpts) error); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueController_QueueResume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueResume'
type MockQueueController_QueueResume_Call struct {
	*mock.Call
}

// QueueResume is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts *river.QueuePauseOpts
func (_e *MockQueueController_Expecter) QueueResume(ctx any, name any, opts any) *MockQueueController_QueueResume_Call {
	return &MockQueueController_QueueResume_Call{Call: _e.mock.On("QueueResume", ctx, name, opts)}
}

func (_c *MockQueueController_QueueResume_Call) Run(run func(ctx context.Context, name string, opts *river.QueuePauseOpts)) *MockQueueController_QueueResume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *river.QueuePauseOpts
		if args[2] != nil {
			arg2 = args[2].(*river.QueuePauseOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueController_QueueResume_Call) Return(err error) *MockQueueController_QueueResume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueController_QueueResume_Call) RunAndReturn(run func(ctx context.Context, name string, opts *river.QueuePauseOpts) error) *MockQueueController_QueueResume_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockThrottler creates a new instance of MockThrottler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThrottler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThrottler {
	mock := &MockThrottler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockThrottler is an autogenerated mock type for the Throttler type
type MockThrottler struct {
	mock.Mock
}

type MockThrottler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThrottler) EXPECT() *MockThrottler_Expecter {
	return &MockThrottler_Expecter{mock: &_m.Mock}
}

// Pause provides a mock function for the type MockThrottler
func (_mock *MockThrottler) Pause(ctx context.Context, pause time.Duration) {
	_mock.Called(ctx, pause)
	return
}

// MockThrottler_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockThrottler_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - pause time.Duration
func (_e *MockThrottler_Expecter) Pause(ctx any, pause any) *MockThrottler_Pause_Call {
	return &MockThrottler_Pause_Call{Call: _e.mock.On("Pause", ctx, pause)}
}

func (_c *MockThrottler_Pause_Call) Run(run func(ctx context.Context, pause time.Duration)) *MockThrottler_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockThrottler_Pause_Call) Return() *MockThrottler_Pause_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockThrottler_Pause_Call) RunAndReturn(run func(ctx context.Context, pause time.Duration)) *MockThrottler_Pause_Call {
	_c.Run(run)
	return _c
}
