// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shigabutdinoff/gophermart/internal/money"
	"github.com/shigabutdinoff/gophermart/internal/order"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreator creates a new instance of MockCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreator {
	mock := &MockCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreator is an autogenerated mock type for the Creator type
type MockCreator struct {
	mock.Mock
}

type MockCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreator) EXPECT() *MockCreator_Expecter {
	return &MockCreator_Expecter{mock: &_m.Mock}
}

// CreateOrFindOwner provides a mock function for the type MockCreator
func (_mock *MockCreator) CreateOrFindOwner(ctx context.Context, number string, userID int64) (order.CreateOutcome, error) {
	ret := _mock.Called(ctx, number, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrFindOwner")
	}

	var r0 order.CreateOutcome
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (order.CreateOutcome, error)); ok {
		return returnFunc(ctx, number, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) order.CreateOutcome); ok {
		r0 = returnFunc(ctx, number, userID)
	} else {
		r0 = ret.Get(0).(order.CreateOutcome)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, number, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreator_CreateOrFindOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrFindOwner'
type MockCreator_CreateOrFindOwner_Call struct {
	*mock.Call
}

// CreateOrFindOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - userID int64
func (_e *MockCreator_Expecter) CreateOrFindOwner(ctx any, number any, userID any) *MockCreator_CreateOrFindOwner_Call {
	return &MockCreator_CreateOrFindOwner_Call{Call: _e.mock.On("CreateOrFindOwner", ctx, number, userID)}
}

func (_c *MockCreator_CreateOrFindOwner_Call) Run(run func(ctx context.Context, number string, userID int64)) *MockCreator_CreateOrFindOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCreator_CreateOrFindOwner_Call) Return(createOutcome order.CreateOutcome, err error) *MockCreator_CreateOrFindOwner_Call {
	_c.Call.Return(createOutcome, err)
	return _c
}

func (_c *MockCreator_CreateOrFindOwner_Call) RunAndReturn(run func(ctx context.Context, number string, userID int64) (order.CreateOutcome, error)) *MockCreator_CreateOrFindOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResultWriter creates a new instance of MockResultWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResultWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResultWriter {
	mock := &MockResultWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResultWriter is an autogenerated mock type for the ResultWriter type
type MockResultWriter struct {
	mock.Mock
}

type MockResultWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResultWriter) EXPECT() *MockResultWriter_Expecter {
	return &MockResultWriter_Expecter{mock: &_m.Mock}
}

// ApplyResult provides a mock function for the type MockResultWriter
func (_mock *MockResultWriter) ApplyResult(ctx context.Context, number string, status order.Status, accrual *money.Points) (bool, error) {
	ret := _mock.Called(ctx, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for ApplyResult")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, order.Status, *money.Points) (bool, error)); ok {
		return returnFunc(ctx, number, status, accrual)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, order.Status, *money.Points) bool); ok {
		r0 = returnFunc(ctx, number, status, accrual)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, order.Status, *money.Points) error); ok {
		r1 = returnFunc(ctx, number, status, accrual)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResultWriter_ApplyResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyResult'
type MockResultWriter_ApplyResult_Call struct {
	*mock.Call
}

// ApplyResult is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - status order.Status
//   - accrual *money.Points
func (_e *MockResultWriter_Expecter) ApplyResult(ctx any, number any, status any, accrual any) *MockResultWriter_ApplyResult_Call {
	return &MockResultWriter_ApplyResult_Call{Call: _e.mock.On("ApplyResult", ctx, number, status, accrual)}
}

func (_c *MockResultWriter_ApplyResult_Call) Run(run func(ctx context.Context, number string, status order.Status, accrual *money.Points)) *MockResultWriter_ApplyResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 order.Status
		if args[2] != nil {
			arg2 = args[2].(order.Status)
		}
		var arg3 *money.Points
		if args[3] != nil {
			arg3 = args[3].(*money.Points)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResultWriter_ApplyResult_Call) Return(b bool, err error) *MockResultWriter_ApplyResult_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockResultWriter_ApplyResult_Call) RunAndReturn(run func(ctx context.Context, number string, status order.Status, accrual *money.Points) (bool, error)) *MockResultWriter_ApplyResult_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLister creates a new instance of MockLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLister {
	mock := &MockLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLister is an autogenerated mock type for the Lister type
type MockLister struct {
	mock.Mock
}

type MockLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLister) EXPECT() *MockLister_Expecter {
	return &MockLister_Expecter{mock: &_m.Mock}
}

// ListByUser provides a mock function for the type MockLister
func (_mock *MockLister) ListByUser(ctx context.Context, userID int64) ([]order.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]order.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []order.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLister_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockLister_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockLister_Expecter) ListByUser(ctx any, userID any) *MockLister_ListByUser_Call {
	return &MockLister_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockLister_ListByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockLister_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLister_ListByUser_Call) Return(orders []order.Order, err error) *MockLister_ListByUser_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockLister_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]order.Order, error)) *MockLister_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
