// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shigabutdinoff/gophermart/internal/money"
	"github.com/shigabutdinoff/gophermart/internal/order"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResultWriter creates a new instance of MockResultWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResultWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResultWriter {
	mock := &MockResultWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResultWriter is an autogenerated mock type for the ResultWriter type
type MockResultWriter struct {
	mock.Mock
}

type MockResultWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResultWriter) EXPECT() *MockResultWriter_Expecter {
	return &MockResultWriter_Expecter{mock: &_m.Mock}
}

// ApplyResult provides a mock function for the type MockResultWriter
func (_mock *MockResultWriter) ApplyResult(ctx context.Context, number string, status order.Status, accrual *money.Points) (bool, error) {
	ret := _mock.Called(ctx, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for ApplyResult")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, order.Status, *money.Points) (bool, error)); ok {
		return returnFunc(ctx, number, status, accrual)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, order.Status, *money.Points) bool); ok {
		r0 = returnFunc(ctx, number, status, accrual)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, order.Status, *money.Points) error); ok {
		r1 = returnFunc(ctx, number, status, accrual)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResultWriter_ApplyResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyResult'
type MockResultWriter_ApplyResult_Call struct {
	*mock.Call
}

// ApplyResult is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - status order.Status
//   - accrual *money.Points
func (_e *MockResultWriter_Expecter) ApplyResult(ctx any, number any, status any, accrual any) *MockResultWriter_ApplyResult_Call {
	return &MockResultWriter_ApplyResult_Call{Call: _e.mock.On("ApplyResult", ctx, number, status, accrual)}
}

func (_c *MockResultWriter_ApplyResult_Call) Run(run func(ctx context.Context, number string, status order.Status, accrual *money.Points)) *MockResultWriter_ApplyResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 order.Status
		if args[2] != nil {
			arg2 = args[2].(order.Status)
		}
		var arg3 *money.Points
		if args[3] != nil {
			arg3 = args[3].(*money.Points)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResultWriter_ApplyResult_Call) Return(b bool, err error) *MockResultWriter_ApplyResult_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockResultWriter_ApplyResult_Call) RunAndReturn(run func(ctx context.Context, number string, status order.Status, accrual *money.Points) (bool, error)) *MockResultWriter_ApplyResult_Call {
	_c.Call.Return(run)
	return _c
}
