// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/shigabutdinoff/gophermart/internal/jobs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueueThrottle creates a new instance of MockQueueThrottle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueThrottle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueThrottle {
	mock := &MockQueueThrottle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueThrottle is an autogenerated mock type for the queueThrottle type
type MockQueueThrottle struct {
	mock.Mock
}

type MockQueueThrottle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueThrottle) EXPECT() *MockQueueThrottle_Expecter {
	return &MockQueueThrottle_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function for the type MockQueueThrottle
func (_mock *MockQueueThrottle) Attach(queueController jobs.QueueController) error {
	ret := _mock.Called(queueController)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(jobs.QueueController) error); ok {
		r0 = returnFunc(queueController)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueThrottle_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type MockQueueThrottle_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - queueController jobs.QueueController
func (_e *MockQueueThrottle_Expecter) Attach(queueController any) *MockQueueThrottle_Attach_Call {
	return &MockQueueThrottle_Attach_Call{Call: _e.mock.On("Attach", queueController)}
}

func (_c *MockQueueThrottle_Attach_Call) Run(run func(queueController jobs.QueueController)) *MockQueueThrottle_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jobs.QueueController
		if args[0] != nil {
			arg0 = args[0].(jobs.QueueController)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueueThrottle_Attach_Call) Return(err error) *MockQueueThrottle_Attach_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueThrottle_Attach_Call) RunAndReturn(run func(queueController jobs.QueueController) error) *MockQueueThrottle_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// Pause provides a mock function for the type MockQueueThrottle
func (_mock *MockQueueThrottle) Pause(ctx context.Context, pause time.Duration) {
	_mock.Called(ctx, pause)
	return
}

// MockQueueThrottle_Pause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pause'
type MockQueueThrottle_Pause_Call struct {
	*mock.Call
}

// Pause is a helper method to define mock.On call
//   - ctx context.Context
//   - pause time.Duration
func (_e *MockQueueThrottle_Expecter) Pause(ctx any, pause any) *MockQueueThrottle_Pause_Call {
	return &MockQueueThrottle_Pause_Call{Call: _e.mock.On("Pause", ctx, pause)}
}

func (_c *MockQueueThrottle_Pause_Call) Run(run func(ctx context.Context, pause time.Duration)) *MockQueueThrottle_Pause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueThrottle_Pause_Call) Return() *MockQueueThrottle_Pause_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQueueThrottle_Pause_Call) RunAndReturn(run func(ctx context.Context, pause time.Duration)) *MockQueueThrottle_Pause_Call {
	_c.Run(run)
	return _c
}

// Resume provides a mock function for the type MockQueueThrottle
func (_mock *MockQueueThrottle) Resume(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueThrottle_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockQueueThrottle_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockQueueThrottle_Expecter) Resume(context1 any) *MockQueueThrottle_Resume_Call {
	return &MockQueueThrottle_Resume_Call{Call: _e.mock.On("Resume", context1)}
}

func (_c *MockQueueThrottle_Resume_Call) Run(run func(context1 context.Context)) *MockQueueThrottle_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueueThrottle_Resume_Call) Return(err error) *MockQueueThrottle_Resume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueThrottle_Resume_Call) RunAndReturn(run func(context1 context.Context) error) *MockQueueThrottle_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockQueueThrottle
func (_mock *MockQueueThrottle) Stop(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueThrottle_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockQueueThrottle_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockQueueThrottle_Expecter) Stop(context1 any) *MockQueueThrottle_Stop_Call {
	return &MockQueueThrottle_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockQueueThrottle_Stop_Call) Run(run func(context1 context.Context)) *MockQueueThrottle_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueueThrottle_Stop_Call) Return(err error) *MockQueueThrottle_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueThrottle_Stop_Call) RunAndReturn(run func(context1 context.Context) error) *MockQueueThrottle_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRiverLifecycle creates a new instance of MockRiverLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRiverLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRiverLifecycle {
	mock := &MockRiverLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRiverLifecycle is an autogenerated mock type for the riverLifecycle type
type MockRiverLifecycle struct {
	mock.Mock
}

type MockRiverLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRiverLifecycle) EXPECT() *MockRiverLifecycle_Expecter {
	return &MockRiverLifecycle_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) Start(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRiverLifecycle_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRiverLifecycle_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRiverLifecycle_Expecter) Start(context1 any) *MockRiverLifecycle_Start_Call {
	return &MockRiverLifecycle_Start_Call{Call: _e.mock.On("Start", context1)}
}

func (_c *MockRiverLifecycle_Start_Call) Run(run func(context1 context.Context)) *MockRiverLifecycle_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRiverLifecycle_Start_Call) Return(err error) *MockRiverLifecycle_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRiverLifecycle_Start_Call) RunAndReturn(run func(context1 context.Context) error) *MockRiverLifecycle_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) Stop(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRiverLifecycle_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockRiverLifecycle_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRiverLifecycle_Expecter) Stop(context1 any) *MockRiverLifecycle_Stop_Call {
	return &MockRiverLifecycle_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockRiverLifecycle_Stop_Call) Run(run func(context1 context.Context)) *MockRiverLifecycle_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRiverLifecycle_Stop_Call) Return(err error) *MockRiverLifecycle_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRiverLifecycle_Stop_Call) RunAndReturn(run func(context1 context.Context) error) *MockRiverLifecycle_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// StopAndCancel provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) StopAndCancel(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for StopAndCancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRiverLifecycle_StopAndCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAndCancel'
type MockRiverLifecycle_StopAndCancel_Call struct {
	*mock.Call
}

// StopAndCancel is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRiverLifecycle_Expecter) StopAndCancel(context1 any) *MockRiverLifecycle_StopAndCancel_Call {
	return &MockRiverLifecycle_StopAndCancel_Call{Call: _e.mock.On("StopAndCancel", context1)}
}

func (_c *MockRiverLifecycle_StopAndCancel_Call) Run(run func(context1 context.Context)) *MockRiverLifecycle_StopAndCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRiverLifecycle_StopAndCancel_Call) Return(err error) *MockRiverLifecycle_StopAndCancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRiverLifecycle_StopAndCancel_Call) RunAndReturn(run func(context1 context.Context) error) *MockRiverLifecycle_StopAndCancel_Call {
	_c.Call.Return(run)
	return _c
}

// Stopped provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) Stopped() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stopped")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockRiverLifecycle_Stopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stopped'
type MockRiverLifecycle_Stopped_Call struct {
	*mock.Call
}

// Stopped is a helper method to define mock.On call
func (_e *MockRiverLifecycle_Expecter) Stopped() *MockRiverLifecycle_Stopped_Call {
	return &MockRiverLifecycle_Stopped_Call{Call: _e.mock.On("Stopped")}
}

func (_c *MockRiverLifecycle_Stopped_Call) Run(run func()) *MockRiverLifecycle_Stopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRiverLifecycle_Stopped_Call) Return(valCh <-chan struct{}) *MockRiverLifecycle_Stopped_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockRiverLifecycle_Stopped_Call) RunAndReturn(run func() <-chan struct{}) *MockRiverLifecycle_Stopped_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockThrottleLifecycle creates a new instance of MockThrottleLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThrottleLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThrottleLifecycle {
	mock := &MockThrottleLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockThrottleLifecycle is an autogenerated mock type for the throttleLifecycle type
type MockThrottleLifecycle struct {
	mock.Mock
}

type MockThrottleLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThrottleLifecycle) EXPECT() *MockThrottleLifecycle_Expecter {
	return &MockThrottleLifecycle_Expecter{mock: &_m.Mock}
}

// Resume provides a mock function for the type MockThrottleLifecycle
func (_mock *MockThrottleLifecycle) Resume(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThrottleLifecycle_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockThrottleLifecycle_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockThrottleLifecycle_Expecter) Resume(context1 any) *MockThrottleLifecycle_Resume_Call {
	return &MockThrottleLifecycle_Resume_Call{Call: _e.mock.On("Resume", context1)}
}

func (_c *MockThrottleLifecycle_Resume_Call) Run(run func(context1 context.Context)) *MockThrottleLifecycle_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockThrottleLifecycle_Resume_Call) Return(err error) *MockThrottleLifecycle_Resume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThrottleLifecycle_Resume_Call) RunAndReturn(run func(context1 context.Context) error) *MockThrottleLifecycle_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockThrottleLifecycle
func (_mock *MockThrottleLifecycle) Stop(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThrottleLifecycle_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockThrottleLifecycle_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockThrottleLifecycle_Expecter) Stop(context1 any) *MockThrottleLifecycle_Stop_Call {
	return &MockThrottleLifecycle_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockThrottleLifecycle_Stop_Call) Run(run func(context1 context.Context)) *MockThrottleLifecycle_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockThrottleLifecycle_Stop_Call) Return(err error) *MockThrottleLifecycle_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThrottleLifecycle_Stop_Call) RunAndReturn(run func(context1 context.Context) error) *MockThrottleLifecycle_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPendingOrderResumer creates a new instance of MockPendingOrderResumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPendingOrderResumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPendingOrderResumer {
	mock := &MockPendingOrderResumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPendingOrderResumer is an autogenerated mock type for the pendingOrderResumer type
type MockPendingOrderResumer struct {
	mock.Mock
}

type MockPendingOrderResumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPendingOrderResumer) EXPECT() *MockPendingOrderResumer_Expecter {
	return &MockPendingOrderResumer_Expecter{mock: &_m.Mock}
}

// Resume provides a mock function for the type MockPendingOrderResumer
func (_mock *MockPendingOrderResumer) Resume(context1 context.Context) (int, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPendingOrderResumer_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockPendingOrderResumer_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockPendingOrderResumer_Expecter) Resume(context1 any) *MockPendingOrderResumer_Resume_Call {
	return &MockPendingOrderResumer_Resume_Call{Call: _e.mock.On("Resume", context1)}
}

func (_c *MockPendingOrderResumer_Resume_Call) Run(run func(context1 context.Context)) *MockPendingOrderResumer_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPendingOrderResumer_Resume_Call) Return(n int, err error) *MockPendingOrderResumer_Resume_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPendingOrderResumer_Resume_Call) RunAndReturn(run func(context1 context.Context) (int, error)) *MockPendingOrderResumer_Resume_Call {
	_c.Call.Return(run)
	return _c
}
