// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRiverLifecycle creates a new instance of MockRiverLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRiverLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRiverLifecycle {
	mock := &MockRiverLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRiverLifecycle is an autogenerated mock type for the riverLifecycle type
type MockRiverLifecycle struct {
	mock.Mock
}

type MockRiverLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRiverLifecycle) EXPECT() *MockRiverLifecycle_Expecter {
	return &MockRiverLifecycle_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) Start(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRiverLifecycle_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRiverLifecycle_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRiverLifecycle_Expecter) Start(context1 any) *MockRiverLifecycle_Start_Call {
	return &MockRiverLifecycle_Start_Call{Call: _e.mock.On("Start", context1)}
}

func (_c *MockRiverLifecycle_Start_Call) Run(run func(context1 context.Context)) *MockRiverLifecycle_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRiverLifecycle_Start_Call) Return(err error) *MockRiverLifecycle_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRiverLifecycle_Start_Call) RunAndReturn(run func(context1 context.Context) error) *MockRiverLifecycle_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) Stop(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRiverLifecycle_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockRiverLifecycle_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRiverLifecycle_Expecter) Stop(context1 any) *MockRiverLifecycle_Stop_Call {
	return &MockRiverLifecycle_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockRiverLifecycle_Stop_Call) Run(run func(context1 context.Context)) *MockRiverLifecycle_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRiverLifecycle_Stop_Call) Return(err error) *MockRiverLifecycle_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRiverLifecycle_Stop_Call) RunAndReturn(run func(context1 context.Context) error) *MockRiverLifecycle_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// StopAndCancel provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) StopAndCancel(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for StopAndCancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRiverLifecycle_StopAndCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAndCancel'
type MockRiverLifecycle_StopAndCancel_Call struct {
	*mock.Call
}

// StopAndCancel is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockRiverLifecycle_Expecter) StopAndCancel(context1 any) *MockRiverLifecycle_StopAndCancel_Call {
	return &MockRiverLifecycle_StopAndCancel_Call{Call: _e.mock.On("StopAndCancel", context1)}
}

func (_c *MockRiverLifecycle_StopAndCancel_Call) Run(run func(context1 context.Context)) *MockRiverLifecycle_StopAndCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRiverLifecycle_StopAndCancel_Call) Return(err error) *MockRiverLifecycle_StopAndCancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRiverLifecycle_StopAndCancel_Call) RunAndReturn(run func(context1 context.Context) error) *MockRiverLifecycle_StopAndCancel_Call {
	_c.Call.Return(run)
	return _c
}

// Stopped provides a mock function for the type MockRiverLifecycle
func (_mock *MockRiverLifecycle) Stopped() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stopped")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockRiverLifecycle_Stopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stopped'
type MockRiverLifecycle_Stopped_Call struct {
	*mock.Call
}

// Stopped is a helper method to define mock.On call
func (_e *MockRiverLifecycle_Expecter) Stopped() *MockRiverLifecycle_Stopped_Call {
	return &MockRiverLifecycle_Stopped_Call{Call: _e.mock.On("Stopped")}
}

func (_c *MockRiverLifecycle_Stopped_Call) Run(run func()) *MockRiverLifecycle_Stopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRiverLifecycle_Stopped_Call) Return(valCh <-chan struct{}) *MockRiverLifecycle_Stopped_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockRiverLifecycle_Stopped_Call) RunAndReturn(run func() <-chan struct{}) *MockRiverLifecycle_Stopped_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockThrottleLifecycle creates a new instance of MockThrottleLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThrottleLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThrottleLifecycle {
	mock := &MockThrottleLifecycle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockThrottleLifecycle is an autogenerated mock type for the throttleLifecycle type
type MockThrottleLifecycle struct {
	mock.Mock
}

type MockThrottleLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThrottleLifecycle) EXPECT() *MockThrottleLifecycle_Expecter {
	return &MockThrottleLifecycle_Expecter{mock: &_m.Mock}
}

// Resume provides a mock function for the type MockThrottleLifecycle
func (_mock *MockThrottleLifecycle) Resume(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThrottleLifecycle_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockThrottleLifecycle_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockThrottleLifecycle_Expecter) Resume(context1 any) *MockThrottleLifecycle_Resume_Call {
	return &MockThrottleLifecycle_Resume_Call{Call: _e.mock.On("Resume", context1)}
}

func (_c *MockThrottleLifecycle_Resume_Call) Run(run func(context1 context.Context)) *MockThrottleLifecycle_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockThrottleLifecycle_Resume_Call) Return(err error) *MockThrottleLifecycle_Resume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThrottleLifecycle_Resume_Call) RunAndReturn(run func(context1 context.Context) error) *MockThrottleLifecycle_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockThrottleLifecycle
func (_mock *MockThrottleLifecycle) Stop(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockThrottleLifecycle_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockThrottleLifecycle_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockThrottleLifecycle_Expecter) Stop(context1 any) *MockThrottleLifecycle_Stop_Call {
	return &MockThrottleLifecycle_Stop_Call{Call: _e.mock.On("Stop", context1)}
}

func (_c *MockThrottleLifecycle_Stop_Call) Run(run func(context1 context.Context)) *MockThrottleLifecycle_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockThrottleLifecycle_Stop_Call) Return(err error) *MockThrottleLifecycle_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockThrottleLifecycle_Stop_Call) RunAndReturn(run func(context1 context.Context) error) *MockThrottleLifecycle_Stop_Call {
	_c.Call.Return(run)
	return _c
}
